name: Python Package

on:
    push:
      branches: [ main ]

jobs:
    deploy:
       runs-on: ubuntu-latest
       strategy:
         fail-fast: false
         matrix:
            python-version: [3.9]
       steps:
        - uses: actions/checkout@master
        - name: Initialize Python 3.7
          uses: actions/setup-python@v2
          with:
            python-version: ${{matrix.python-version}}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Check docker installed or not
          run: docker run hello-world
        - name: Login TO DockerHub
          uses: docker/login-action@v1
          with:
            # push: true
            # tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            # repository: ${{secrets.DOCKERHUB_REPO}}
            # push: true
            # tags: trojancodes/flask_inventory:latest
        - name: Build and Push To Docker Image
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest



 